### ISSUE TITLE
Readme updates, examples for common use-cases

### ISSUE THREAD

**Issue by sc0ttkclark** [sc0ttkclark/wordpress-fields-api#22]
Update specs with more details on usage of Fields API by third party apps/plugins, refresh readme so it's more clear and concise.
- [x] Main Readme refresh

Objects in order of progress, then by priority:
- [x] Users #29 @sc0ttkclark
- [x] Terms #28 @technosailor
- [ ] Settings API #33 @technosailor
- [ ] Posts #26 @sc0ttkclark + @idealien
- [ ] Comment #31 @sc0ttkclark
- [ ] Nav Menu Items #34 @diddledan
- [ ] Widgets #27 @nicholasio
- [ ] Media #32 @wpsmith

**Comment by sc0ttkclark** [comment]
@tomharrigan and @nicholasio you are now owners of the use-cases / examples for your associated areas. Please flesh out 3-5 section + fields examples for each of your implementations and save them into /examples/{implementation}/{example}.md in the Repo

**Comment by sc0ttkclark** [comment]
@wpsmith is now heading up the media prototype, you are also now in charge of the use-cases / examples for your associated area. Please flesh out 3-5 section + fields examples for your implementation and save them into /examples/media/{example}.md in the Repo.

**Comment by Mte90** [comment]
Example are very interesting to evaluate the level of that feature plugin

**Comment by Mte90** [comment]
To start on that i've studied the test files but i don't understand how to use the library.
I have to try with a phpdoc generation but without an example is very difficult to start.

**Comment by overclokk** [comment]
Me too

**Comment by sc0ttkclark** [comment]
Here's the current User Edit screen implementation, it's the best example I have right now for you as it's been my primary focus on testing the limits of the Fields API.

https://github.com/sc0ttkclark/wordpress-fields-api/blob/master/implementation/wp-admin/includes/class-wp-fields-api-user-profile.php

**Comment by msykes** [comment]
A typical example of a user section containing address information would be helpful, so for example:

section – address
 - address 1 (text)
 - address 2 (text)
 - town/city (text)
 - county/state (text)
 - Zip (text)
 - country (DDM)

**Comment by sc0ttkclark** [comment]
Here's an example of address fields for a User profile:

```php
///////////////////////////
// Example: User Address //
///////////////////////////
		
$wp_fields->add_section( 'user', 'my-address', 'edit-profile', array(
	'title' => __( 'Address' ),
) );

$field_args = array(
	'control' => array(
		'type'        => 'text',
		'section'     => 'my-address',
		'label'       => __( 'Address 1' ),
	),
);

$wp_fields->add_field( 'user', 'address_1', 'edit-profile', $field_args );

$field_args = array(
	'control' => array(
		'type'        => 'text',
		'section'     => 'my-address',
		'label'       => __( 'Address 2' ),
	),
);

$wp_fields->add_field( 'user', 'address_2', 'edit-profile', $field_args );

$field_args = array(
	'control' => array(
		'type'        => 'text',
		'section'     => 'my-address',
		'label'       => __( 'City' ),
	),
);

$wp_fields->add_field( 'user', 'address_city', 'edit-profile', $field_args );

$field_args = array(
	'control' => array(
		'type'        => 'text',
		'section'     => 'my-address',
		'label'       => __( 'State / County' ),
	),
);

$wp_fields->add_field( 'user', 'address_state', 'edit-profile', $field_args );

$field_args = array(
	'control' => array(
		'type'        => 'text',
		'section'     => 'my-address',
		'label'       => __( 'Zip / Postal Code' ),
	),
);

$wp_fields->add_field( 'user', 'address_zip', 'edit-profile', $field_args );

$field_args = array(
	'control' => array(
		'type'        => 'select',
		'section'     => 'my-address',
		'label'       => __( 'Country' ),
		'choices' => array(
			'US' => 'United States',
			'CA' => 'Canada',
		)
	),
);

$wp_fields->add_field( 'user', 'address_country', 'edit-profile', $field_args );
```

**Comment by sc0ttkclark** [comment]
That doesn't include the action to call this on and when, but it's example code of how to add it to the Fields API

**Comment by sc0ttkclark** [comment]
Added address example to my new examples and docs pages that are about to go up :)

**Comment by sc0ttkclark** [comment]
Added new doc page for Creating an Implementation (useful for those coming to help out with what we've got going already, based on User / Term screens we did) -- https://github.com/sc0ttkclark/wordpress-fields-api/blob/master/docs/creating-an-implementation.md

Added some new examples too --

**User Profile Screen:**

* [Starter example](https://github.com/sc0ttkclark/wordpress-fields-api/blob/master/docs/examples/user/_starter.php)
* [Address section and fields example](https://github.com/sc0ttkclark/wordpress-fields-api/blob/master/docs/examples/user/address.php)

**Term Add / Edit Screen:**

* [Starter example](https://github.com/sc0ttkclark/wordpress-fields-api/blob/master/docs/examples/term/_starter.php)

I would *love to get some more use-cases* so I can add more examples!

**Comment by sc0ttkclark** [comment]
Added new doc page for Registering Fields and it's pretty comprehensive in walking you through what everything is and how to pull it all together.

https://github.com/sc0ttkclark/wordpress-fields-api/blob/master/docs/registering-fields.md

Also updated the main README.md to link to these new docs/examples:

https://github.com/sc0ttkclark/wordpress-fields-api/blob/master/README.md

**Comment by diddledan** [comment]
Example fields for a CPT for "products" being sold (this is probably one of the more complex scenarios I can think of quickly):

- Price (floating point numeric / text-field with validation or cast-to-float),
- Taxable (boolean / checkbox),
- Customizations (uses fields-api to display configuration selections for front-end output which would also be driven by fields-api)
  - expandable array of text-fields
  - each text-field associated with dropdown listing available field-types registered to the fields-api, for the admin to choose for front-end display
  - include expandable nested array for multiple-choices when the fields api shows on the front-end

**Comment by iamhexcoder** [comment]
Pages - I often need a subtitle and page header text separate from content.

What is the possibility for having a 'repeater' style field (a la ACF) on a page or custom post type? This would involve more than just the fields API (as I'm sure js would be required), but its a situation I often require. Use case: a page has a staff section, rather than making a custom post type, you just build a series of fields (name, position, email, etc) that can be added and deleted.

**Comment by szepeviktor** [comment]
Could you add
- [ ] Repeatable field implementation example?
